config/routes.rb
Rails.application.routes.draw do
  resources :experiments
  root 'experiments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_many :steps, dependent: :destroy

  def percentage_completed
    num_completed = steps.where(completed: true).count
    num_total = steps.count

    percentage = num_completed.to_f / num_total * 100
    (percentage.nan?) ? "0%" : "#{percentage.to_i}%"
  end
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :experiment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experiment_params
      params.require(:experiment).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiments/_form.html.erb
<%= form_with(model: experiment, local: true) do |form| %>
  <% if experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
        <% experiment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing Experiment</h1>

<%= render 'form', experiment: @experiment %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Steps Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiments.each do |experiment| %>
      <%= content_tag :tr, id: "experiment_#{experiment.id}" do %>
        <td><%= experiment.name %></td>
        <td><%= experiment.description %></td>
        <td><%= experiment.percentage_completed %></td>
        <td><%= link_to 'Show', experiment %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
        <td><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experiment', new_experiment_path %>

app/views/experiments/new.html.erb
<h1>New Experiment</h1>

<%= render 'form', experiment: @experiment %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiment Details</h1>

<p>
  <strong>Name:</strong>
  <%= @experiment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experiment.description %>
</p>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>

<h3>Steps</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @experiment.steps.each do |step| %>
      <%= content_tag :tr, id: "step_#{step.id}" do %>
        <td><%= step.name %></td>
        <td><%= (step.completed?) ? 'Complete' : 'Incomplete' %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Genofab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>